"""
YouTube Data API v3 client for fetching real, verified video links.

This service:
1. Takes search queries (generated by Gemini or curated)
2. Calls YouTube Data API to get real videos
3. Returns verified video URLs that are guaranteed to work

Requires YOUTUBE_API_KEY environment variable.
Free tier: 10,000 units/day (search costs 100 units = 100 searches/day)
"""

import logging
import urllib.parse
from typing import Dict, Any, List, Optional
from dataclasses import dataclass
import httpx

from ..config import settings

logger = logging.getLogger(__name__)


@dataclass
class YouTubeVideo:
    """Represents a YouTube video with verified data."""
    video_id: str
    title: str
    channel_name: str
    description: str
    thumbnail_url: str
    url: str
    duration: Optional[str] = None
    view_count: Optional[int] = None
    published_at: Optional[str] = None


class YouTubeClient:
    """
    Client for YouTube Data API v3.
    
    Uses the search endpoint to find videos matching queries,
    returning real, verified video IDs and URLs.
    """
    
    BASE_URL = "https://www.googleapis.com/youtube/v3"
    
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or getattr(settings, 'youtube_api_key', None)
        self._client = httpx.Client(timeout=10.0)
        
        if not self.api_key:
            logger.warning("YouTube API key not configured - will use fallback search URLs")
    
    def is_available(self) -> bool:
        """Check if the YouTube API is configured and available."""
        return bool(self.api_key)
    
    def search_videos(
        self,
        query: str,
        max_results: int = 3,
        video_duration: str = "any",  # "any", "short" (<4min), "medium" (4-20min), "long" (>20min)
        order: str = "relevance",  # "relevance", "viewCount", "rating", "date"
        safe_search: str = "moderate"
    ) -> List[YouTubeVideo]:
        """
        Search YouTube for videos matching the query.
        
        Args:
            query: Search query string
            max_results: Maximum number of videos to return (1-50)
            video_duration: Filter by duration
            order: How to order results
            safe_search: Content safety filter
        
        Returns:
            List of YouTubeVideo objects with verified URLs
        """
        if not self.api_key:
            logger.warning("YouTube API not configured, returning empty results")
            return []
        
        try:
            params = {
                "part": "snippet",
                "q": query,
                "type": "video",
                "maxResults": min(max_results, 10),
                "order": order,
                "safeSearch": safe_search,
                "videoDuration": video_duration,
                "relevanceLanguage": "en",
                "key": self.api_key
            }
            
            response = self._client.get(
                f"{self.BASE_URL}/search",
                params=params
            )
            
            if response.status_code == 403:
                logger.error("YouTube API quota exceeded or invalid key")
                return []
            
            response.raise_for_status()
            data = response.json()
            
            videos = []
            for item in data.get("items", []):
                video_id = item.get("id", {}).get("videoId")
                if not video_id:
                    continue
                
                snippet = item.get("snippet", {})
                
                videos.append(YouTubeVideo(
                    video_id=video_id,
                    title=snippet.get("title", ""),
                    channel_name=snippet.get("channelTitle", ""),
                    description=snippet.get("description", "")[:200],
                    thumbnail_url=snippet.get("thumbnails", {}).get("medium", {}).get("url", ""),
                    url=f"https://www.youtube.com/watch?v={video_id}",
                    published_at=snippet.get("publishedAt")
                ))
            
            logger.info(f"YouTube API returned {len(videos)} videos for query: {query[:50]}")
            return videos
            
        except httpx.HTTPStatusError as e:
            logger.error(f"YouTube API HTTP error: {e.response.status_code}")
            return []
        except Exception as e:
            logger.error(f"YouTube API error: {e}")
            return []
    
    def search_educational_videos(
        self,
        skill: str,
        level: str,
        topic: Optional[str] = None,
        max_results: int = 3
    ) -> List[YouTubeVideo]:
        """
        Search for educational videos tailored to skill and level.
        
        Args:
            skill: The skill being learned (e.g., "Python", "React")
            level: Learner level ("beginner", "intermediate", "advanced")
            topic: Optional specific topic within the skill
            max_results: Maximum videos to return
        
        Returns:
            List of verified YouTubeVideo objects
        """
        # Build optimized educational search query
        level_keywords = {
            "beginner": "tutorial for beginners complete course",
            "intermediate": "tutorial intermediate projects",
            "advanced": "advanced tutorial deep dive"
        }
        
        level_terms = level_keywords.get(level.lower(), level_keywords["beginner"])
        
        if topic:
            query = f"{skill} {topic} {level_terms}"
        else:
            query = f"{skill} {level_terms}"
        
        # Prefer medium-length videos for tutorials
        duration = "medium" if level == "beginner" else "any"
        
        return self.search_videos(
            query=query,
            max_results=max_results,
            video_duration=duration,
            order="relevance"
        )
    
    def get_video_details(self, video_id: str) -> Optional[YouTubeVideo]:
        """
        Get detailed information about a specific video.
        
        Args:
            video_id: YouTube video ID
        
        Returns:
            YouTubeVideo with full details, or None if not found
        """
        if not self.api_key:
            return None
        
        try:
            params = {
                "part": "snippet,contentDetails,statistics",
                "id": video_id,
                "key": self.api_key
            }
            
            response = self._client.get(
                f"{self.BASE_URL}/videos",
                params=params
            )
            response.raise_for_status()
            data = response.json()
            
            items = data.get("items", [])
            if not items:
                return None
            
            item = items[0]
            snippet = item.get("snippet", {})
            stats = item.get("statistics", {})
            
            return YouTubeVideo(
                video_id=video_id,
                title=snippet.get("title", ""),
                channel_name=snippet.get("channelTitle", ""),
                description=snippet.get("description", "")[:500],
                thumbnail_url=snippet.get("thumbnails", {}).get("medium", {}).get("url", ""),
                url=f"https://www.youtube.com/watch?v={video_id}",
                published_at=snippet.get("publishedAt"),
                view_count=int(stats.get("viewCount", 0)) if stats.get("viewCount") else None
            )
            
        except Exception as e:
            logger.error(f"Error getting video details: {e}")
            return None
    
    def verify_video_exists(self, video_id: str) -> bool:
        """
        Verify that a video ID exists and is accessible.
        
        Args:
            video_id: YouTube video ID to verify
        
        Returns:
            True if video exists and is accessible
        """
        if not self.api_key:
            return False
        
        video = self.get_video_details(video_id)
        return video is not None
    
    def close(self):
        """Close the HTTP client."""
        self._client.close()


class MockYouTubeClient:
    """
    Mock YouTube client for testing without API key.
    Returns realistic-looking but fake video data.
    """
    
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key
    
    def is_available(self) -> bool:
        return True  # Mock is always "available"
    
    def search_videos(
        self,
        query: str,
        max_results: int = 3,
        **kwargs
    ) -> List[YouTubeVideo]:
        """Return mock videos based on query."""
        # Generate mock videos based on query terms
        base_title = query.split()[0].title() if query else "Programming"
        
        mock_videos = [
            YouTubeVideo(
                video_id="dQw4w9WgXcQ",  # Famous video ID for testing
                title=f"{base_title} Complete Tutorial for Beginners",
                channel_name="freeCodeCamp.org",
                description=f"Learn {base_title} from scratch in this comprehensive tutorial.",
                thumbnail_url="https://i.ytimg.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
                url="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
            ),
            YouTubeVideo(
                video_id="rfscVS0vtbw",
                title=f"{base_title} Full Course - Learn in 4 Hours",
                channel_name="freeCodeCamp.org",
                description=f"Master {base_title} with this full course tutorial.",
                thumbnail_url="https://i.ytimg.com/vi/rfscVS0vtbw/mqdefault.jpg",
                url="https://www.youtube.com/watch?v=rfscVS0vtbw"
            ),
            YouTubeVideo(
                video_id="8mAITcNt710",
                title=f"{base_title} Crash Course",
                channel_name="Traversy Media",
                description=f"Quick crash course on {base_title} fundamentals.",
                thumbnail_url="https://i.ytimg.com/vi/8mAITcNt710/mqdefault.jpg",
                url="https://www.youtube.com/watch?v=8mAITcNt710"
            )
        ]
        
        return mock_videos[:max_results]
    
    def search_educational_videos(
        self,
        skill: str,
        level: str,
        topic: Optional[str] = None,
        max_results: int = 3
    ) -> List[YouTubeVideo]:
        """Return mock educational videos."""
        query = f"{skill} {topic or ''} {level}".strip()
        return self.search_videos(query, max_results)
    
    def verify_video_exists(self, video_id: str) -> bool:
        return True  # Mock always returns True
    
    def close(self):
        pass


# Module-level client instance
_youtube_client: Optional[YouTubeClient] = None


def get_youtube_client() -> YouTubeClient:
    """Get or create the YouTube API client."""
    global _youtube_client
    
    if _youtube_client is None:
        api_key = getattr(settings, 'youtube_api_key', None)
        
        if api_key:
            _youtube_client = YouTubeClient(api_key)
            logger.info("YouTube API client initialized with API key")
        else:
            _youtube_client = MockYouTubeClient()
            logger.warning("YouTube API key not found - using mock client")
    
    return _youtube_client


def set_youtube_client(client):
    """Set a custom YouTube client (for testing)."""
    global _youtube_client
    _youtube_client = client
